host: ""
auth: ""
cidr: "172.64.225.0/20"
t_num: 100
speed_num: 10
speed_limit: 0.5
ray:
  - "NRT"
  - "SIN"
  - "ICN"
  - "TYO"



#	"NRT": "🇯🇵 日本-东京/成田",
#	"TYO": "🇯🇵 日本-东京",
#	"KIX": "🇯🇵 日本-大阪",
#	"SIN": "🇸🇬 新加坡-新加坡",
#	"HKG": "🇭🇰 中国香港-香港",
#	"ICN": "🇰🇷 韩国-首尔",
#	"LAX": "🇺🇸 美国-洛杉矶",
#	"SJC": "🇺🇸 美国-圣何塞",
#	"SEA": "🇺🇸 美国-西雅图",
#	"FRA": "🇩🇪 德国-法兰克福",
#	"LHR": "🇬🇧 英国-伦敦",
#	"AMS": "🇳🇱荷兰-阿姆斯特丹",
#	"DEN": "🇺🇸美国-科罗拉多州丹佛",
